In [ ]:
import tensorflow as tf




In [ ]:
tf.__version__

'2.6.0'

In [ ]:
tf.test.gpu_device_name()

'/device:GPU:0'

In [ ]:
X = tf.constant([-1,3,2.6,4.3,-0.8]) #Create a tensor with 5 numbers

In [ ]:
X.shape # the shape of the tensor X

TensorShape([5])

In [ ]:
X

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([-1. ,  3. ,  2.6,  4.3, -0.8], dtype=float32)>

In [ ]:
for item in X:  #print each value in the tensor X
  print(item)

tf.Tensor(-1.0, shape=(), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(2.6, shape=(), dtype=float32)
tf.Tensor(4.3, shape=(), dtype=float32)
tf.Tensor(-0.8, shape=(), dtype=float32)


In [ ]:
X[0]

<tf.Tensor: shape=(), dtype=float32, numpy=-1.0>

In [ ]:
X.numpy() #Extract the values in the tensor X as numpy array

array([-1. ,  3. ,  2.6,  4.3, -0.8], dtype=float32)

In [ ]:
X[1:4].numpy()  #return values stored at index 1,2,3

array([3. , 2.6, 4.3], dtype=float32)

In [ ]:
tf.math.reduce_max(X).numpy() #get the maximum value in tensor X

4.3

In [ ]:
tf.math.argmax(X).numpy() #get the index that contains the maximum value in tensor X

3

In [ ]:
Y = tf.constant([0,2.1,-1,0.3,1]) #Creating another tensor with 5 values

In [ ]:
Y

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 0. ,  2.1, -1. ,  0.3,  1. ], dtype=float32)>

In [ ]:
tf.math.greater(X,Y) #Check location by location if X is greater than Y

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False,  True,  True,  True, False])>

In [ ]:
tf.math.equal(X,Y) #Check location by location if X is equal to Y

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False, False, False, False, False])>

In [ ]:
Z = tf.constant([[3,9.0,1.2],[-2,2.1,8]]) #create a 2D Tensor Z
ZZ = tf.constant([[4,10.0,-1],[-3,3.8,4]]) #create another 2D Tensor ZZ

In [ ]:
Z

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 3. ,  9. ,  1.2],
       [-2. ,  2.1,  8. ]], dtype=float32)>

In [ ]:
ZZ

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 4. , 10. , -1. ],
       [-3. ,  3.8,  4. ]], dtype=float32)>

In [ ]:
Z.numpy()

array([[ 3. ,  9. ,  1.2],
       [-2. ,  2.1,  8. ]], dtype=float32)

In [ ]:
tf.math.add(Z,ZZ)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 7.        , 19.        ,  0.20000005],
       [-5.        ,  5.8999996 , 12.        ]], dtype=float32)>

In [ ]:
tf.math.reduce_max(ZZ).numpy()

10.0

In [ ]:
Z

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 3. ,  9. ,  1.2],
       [-2. ,  2.1,  8. ]], dtype=float32)>

In [ ]:
tf.math.argmax(Z,0)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 0, 1])>

In [ ]:
tf.math.argmax(Z,1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 2])>

In [ ]:
tf.rank(Z) #number of indices needed to uniquely identify a value in the tensor

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tf.rank(X) #rank of X, number of indices needed to uniquely identify a value in the tensor

<tf.Tensor: shape=(), dtype=int32, numpy=1>