In [ ]:
from sklearn import datasets

iris = datasets.load_iris()


In [ ]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
X = iris['data']

In [ ]:
X.shape

(150, 4)

In [ ]:
y = iris['target']

In [ ]:
y.shape

(150,)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.33, random_state = 42)

In [ ]:
X_train.shape

(100, 4)

In [ ]:
y_train.shape

(100,)

In [ ]:
X_test.shape

(50, 4)

In [ ]:
y_test.shape

(50,)

In [ ]:
import numpy as np


In [ ]:
y_train_virginica = (y_train == 2).astype(int)

In [ ]:
y_train_virginica

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1])

In [ ]:
y_test_virginica = (y_test == 2).astype(int)

In [ ]:
y_test_virginica

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1])

In [ ]:
X_train_oneF = X_train[:,3]

In [ ]:
X_test_oneF = X_test[:,3]

In [ ]:
from sklearn.linear_model import LogisticRegression
log_reg_oneF = LogisticRegression()
log_reg_oneF.fit(X_train_oneF.reshape(-1,1), y_train_virginica)

LogisticRegression()

In [ ]:
log_reg_oneF.coef_

array([[3.72350587]])

In [ ]:
log_reg_oneF.intercept_

array([-6.16356032])

In [ ]:
y_predict_virginica = log_reg_oneF.predict(X_test_oneF.reshape(-1,1))

In [ ]:
y_predict_virginica

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1])

In [ ]:
y_proba = log_reg_oneF.predict_proba(X_test_oneF.reshape(-1,1))

In [ ]:
print(y_proba)

[[0.84492687 0.15507313]
 [0.99360935 0.00639065]
 [0.08313433 0.91686567]
 [0.64067649 0.35932351]
 [0.7212463  0.2787537 ]
 [0.99075293 0.00924707]
 [0.78968084 0.21031916]
 [0.08313433 0.91686567]
 [0.64067649 0.35932351]
 [0.84492687 0.15507313]
 [0.21696329 0.78303671]
 [0.99695502 0.00304498]
 [0.99558736 0.00441264]
 [0.99695502 0.00304498]
 [0.99360935 0.00639065]
 [0.55130651 0.44869349]
 [0.11627862 0.88372138]
 [0.88772431 0.11227569]
 [0.78968084 0.21031916]
 [0.11627862 0.88372138]
 [0.99558736 0.00441264]
 [0.36847835 0.63152165]
 [0.99075293 0.00924707]
 [0.16032633 0.83967367]
 [0.21696329 0.78303671]
 [0.08313433 0.91686567]
 [0.36847835 0.63152165]
 [0.08313433 0.91686567]
 [0.99360935 0.00639065]
 [0.99558736 0.00441264]
 [0.99558736 0.00441264]
 [0.99075293 0.00924707]
 [0.7212463  0.2787537 ]
 [0.99558736 0.00441264]
 [0.99558736 0.00441264]
 [0.28677462 0.71322538]
 [0.64067649 0.35932351]
 [0.99558736 0.00441264]
 [0.99558736 0.00441264]
 [0.99695502 0.00304498]


Binary Classifier using all 4 features (sepal length, sepal width, petal length, petal width)


In [ ]:
log_reg_allF = LogisticRegression()
log_reg_allF.fit(X_train,y_train_virginica)
#training with all 4 features to classify virginica vs not virginica

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
log_reg_allF.coef_ #This gives us the values of B1,B2,B3,B4

array([[-0.27113898, -0.36966884,  2.51348032,  2.02545183]])

In [ ]:
log_reg_allF.intercept_ #this is gives us Bo

array([-12.92101707])

In [ ]:
log_reg_allF.predict(X_test)

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1])

In [ ]:
log_reg_allF.predict_proba(X_test)

array([[7.96755454e-01, 2.03244546e-01],
       [9.99983143e-01, 1.68574882e-05],
       [2.39582907e-03, 9.97604171e-01],
       [7.80922675e-01, 2.19077325e-01],
       [7.10846078e-01, 2.89153922e-01],
       [9.99984297e-01, 1.57030422e-05],
       [9.78747901e-01, 2.12520987e-02],
       [1.76616781e-01, 8.23383219e-01],
       [7.43932837e-01, 2.56067163e-01],
       [9.62981398e-01, 3.70186016e-02],
       [2.68294554e-01, 7.31705446e-01],
       [9.99990926e-01, 9.07413839e-06],
       [9.99994058e-01, 5.94171025e-06],
       [9.99989057e-01, 1.09429325e-05],
       [9.99988001e-01, 1.19985660e-05],
       [6.88908069e-01, 3.11091931e-01],
       [3.76243674e-02, 9.62375633e-01],
       [9.65543623e-01, 3.44563773e-02],
       [8.26042208e-01, 1.73957792e-01],
       [5.51950860e-02, 9.44804914e-01],
       [9.99982471e-01, 1.75287318e-05],
       [4.30969796e-01, 5.69030204e-01],
       [9.99977497e-01, 2.25030597e-05],
       [6.67599345e-02, 9.33240066e-01],
       [2.485757